# TASK #1: UNDERSTAND THE PROBLEM STATEMENT/GOAL



- This dataset contains weekly sales from 99 departments belonging to 45 different stores. 
- Our aim is to forecast weekly sales from a particular department.
- The objective of this case study is to forecast weekly retail store sales based on historical data.
- The data contains holidays and promotional markdowns offered by various stores and several departments throughout the year.
- Markdowns are crucial to promote sales especially before key events such as Super Bowl, Christmas and Thanksgiving. 
- Developing accurate model will enable make informed decisions and make recommendations to improve business processes in the future. 
- The data consists of three sheets: 
    - Stores
    - Features
    - Sales
- Data Source : https://www.kaggle.com/manjeetsingh/retaildataset

# TASK #2: IMPORT DATASET AND LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import zipfile


In [2]:
df = pd.read_csv('../data/data_processed.csv')
df.head()

Store  Dept        Date  Weekly_Sales  IsHoliday  Temperature  Fuel_Price  \
0      1     1  2010-05-02      24924.50          0        42.31       2.572   
1      1     2  2010-05-02      50605.27          0        42.31       2.572   
2      1     3  2010-05-02      13740.12          0        42.31       2.572   
3      1     4  2010-05-02      39954.04          0        42.31       2.572   
4      1     5  2010-05-02      32229.38          0        42.31       2.572   

   MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  \
0        0.0        0.0        0.0        0.0        0.0  211.096358   
1        0.0        0.0        0.0        0.0        0.0  211.096358   
2        0.0        0.0        0.0        0.0        0.0  211.096358   
3        0.0        0.0        0.0        0.0        0.0  211.096358   
4        0.0        0.0        0.0        0.0        0.0  211.096358   

   Unemployment  month Type    Size  
0         8.106      5    A  151315  
1         8.106      5    A  151315  
2         8.106      5    A  151315  
3         8.106      5    A  151315  
4         8.106      5    A  151315

In [3]:
# Drop the date
y = df['Weekly_Sales'] # target
X = df.drop(columns = ['Weekly_Sales', 'Date']) # features

In [4]:
X = pd.get_dummies(X, columns = ['Type', 'Store', 'Dept'], drop_first = True)

In [5]:
X.shape

(421570, 138)

In [6]:
y.shape

(421570,)

In [7]:
X.head()

IsHoliday  Temperature  Fuel_Price  MarkDown1  MarkDown2  MarkDown3  \
0          0        42.31       2.572        0.0        0.0        0.0   
1          0        42.31       2.572        0.0        0.0        0.0   
2          0        42.31       2.572        0.0        0.0        0.0   
3          0        42.31       2.572        0.0        0.0        0.0   
4          0        42.31       2.572        0.0        0.0        0.0   

   MarkDown4  MarkDown5         CPI  Unemployment  ...  Dept_90  Dept_91  \
0        0.0        0.0  211.096358         8.106  ...        0        0   
1        0.0        0.0  211.096358         8.106  ...        0        0   
2        0.0        0.0  211.096358         8.106  ...        0        0   
3        0.0        0.0  211.096358         8.106  ...        0        0   
4        0.0        0.0  211.096358         8.106  ...        0        0   

   Dept_92  Dept_93  Dept_94  Dept_95  Dept_96  Dept_97  Dept_98  Dept_99  
0        0        0        0        0        0        0        0        0  
1        0        0        0        0        0        0        0        0  
2        0        0        0        0        0        0        0        0  
3        0        0        0        0        0        0        0        0  
4        0        0        0        0        0        0        0        0  

[5 rows x 138 columns]

In [8]:
# save columnames for later purposes
featurenames = list(X.columns)
featurenames

['IsHoliday',
 'Temperature',
 'Fuel_Price',
 'MarkDown1',
 'MarkDown2',
 'MarkDown3',
 'MarkDown4',
 'MarkDown5',
 'CPI',
 'Unemployment',
 'month',
 'Size',
 'Type_B',
 'Type_C',
 'Store_2',
 'Store_3',
 'Store_4',
 'Store_5',
 'Store_6',
 'Store_7',
 'Store_8',
 'Store_9',
 'Store_10',
 'Store_11',
 'Store_12',
 'Store_13',
 'Store_14',
 'Store_15',
 'Store_16',
 'Store_17',
 'Store_18',
 'Store_19',
 'Store_20',
 'Store_21',
 'Store_22',
 'Store_23',
 'Store_24',
 'Store_25',
 'Store_26',
 'Store_27',
 'Store_28',
 'Store_29',
 'Store_30',
 'Store_31',
 'Store_32',
 'Store_33',
 'Store_34',
 'Store_35',
 'Store_36',
 'Store_37',
 'Store_38',
 'Store_39',
 'Store_40',
 'Store_41',
 'Store_42',
 'Store_43',
 'Store_44',
 'Store_45',
 'Dept_2',
 'Dept_3',
 'Dept_4',
 'Dept_5',
 'Dept_6',
 'Dept_7',
 'Dept_8',
 'Dept_9',
 'Dept_10',
 'Dept_11',
 'Dept_12',
 'Dept_13',
 'Dept_14',
 'Dept_16',
 'Dept_17',
 'Dept_18',
 'Dept_19',
 'Dept_20',
 'Dept_21',
 'Dept_22',
 'Dept_23',
 'Dept_24',

In [9]:
X = np.array(X).astype('float32')
y = np.array(y).astype('float32')

In [10]:
# reshaping the array from (421570,) to (421570, 1)
y = y.reshape(-1,1)
y.shape

(421570, 1)

In [11]:
# scaling the data before feeding the model
# from sklearn.preprocessing import StandardScaler, MinMaxScaler

# scaler_x = StandardScaler()
# X = scaler_x.fit_transform(X)

# scaler_y = StandardScaler()
# y = scaler_y.fit_transform(y)

In [12]:
# spliting the data in to train, validation and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size = 0.5)

In [13]:
X_train.shape

(210785, 138)

In [14]:
X_val.shape

(105393, 138)

In [15]:
X_test.shape

(105392, 138)

# TASK #9: TRAIN XGBOOST REGRESSOR IN LOCAL MODE

In [16]:
!pip install xgboost

Keyring is skipped due to an exception: 'keyring.backends'


In [17]:
%%time
# Train an XGBoost regressor model 
import xgboost as xgb
model = xgb.XGBRegressor(objective ='reg:squarederror', 
                         learning_rate = 0.1, 
                         max_depth = 2,
                         n_estimators = 10)
model.fit(X_train, y_train)

CPU times: user 15.7 s, sys: 425 ms, total: 16.1 s
Wall time: 1.16 s


XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:squarederror',
             predictor='auto', random_state=0, reg_alpha=0, ...)

In [18]:
type(model)

xgboost.sklearn.XGBRegressor

In [19]:
# predict the score of the trained model using the testing dataset
result = model.score(X_test, y_test)
print("R2 on test set : {}".format(result))

R2 on test set : 0.19377960084464463


In [20]:
# make predictions on the test data
y_predict = model.predict(X_test)
y_predict

array([ 8919.375 ,  8115.5186,  8115.5186, ...,  8115.5186, 43860.434 ,
        8115.5186], dtype=float32)

In [21]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from math import sqrt
k = X_test.shape[1]
n = len(X_test)
RMSE = float(format(np.sqrt(mean_squared_error(y_test, y_predict)),'.3f'))
MSE = mean_squared_error(y_test, y_predict)
MAE = mean_absolute_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)

print('RMSE =',RMSE, '\nMSE =',MSE, '\nMAE =',MAE, '\nR2 =', r2, '\nAdjusted R2 =', adj_r2) 

RMSE = 20396.621 
MSE = 416022140.0 
MAE = 12216.002 
R2 = 0.19377960084464463 
Adjusted R2 = 0.19272254389535626


# TASK #12: PERFORM HYPERPARAMETERS OPTIMIZATION

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
model

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:squarederror',
             predictor='auto', random_state=0, reg_alpha=0, ...)

In [24]:
# Define our search space for grid search
search_space = {
    'clf__n_estimators': [25, 50, 100],
    'clf__max_depth': [4, 6, 8],
    'clf__colsample_bytree': [0.1, 0.2]
    }

In [25]:
%%time
clf = GridSearchCV(estimator = model, 
                   param_grid= search_space, 
                   scoring='r2',
                   cv=5,
                   n_jobs=-1)
clf.fit(X_train, y_train)

[15:40:20] WARNING: ../src/learner.cc:627: 
Parameters: { "clf__colsample_bytree", "clf__max_depth", "clf__n_estimators" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


CPU times: user 16.2 s, sys: 660 ms, total: 16.9 s
Wall time: 47.7 s


GridSearchCV(cv=5, error_score=nan,
             estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                    callbacks=None, colsample_bylevel=1,
                                    colsample_bynode=1, colsample_bytree=1,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    gamma=0, gpu_id=-1, grow_policy='depthwise',
                                    importance_type=None,
                                    interaction_constraints='',
                                    learning_rate=0.1, max_bin=256...
                                    monotone_constraints='()', n_estimators=10,
                                    n_jobs=0, num_parallel_tree=1,
                                    objective='reg:squarederror',
                                    predictor='auto', random_state=0,
                                    reg_alpha

In [26]:
# show best xgboost parameters
clf.best_params_

{'clf__colsample_bytree': 0.1, 'clf__max_depth': 4, 'clf__n_estimators': 25}

In [27]:
tuned_model = clf.best_estimator_
tuned_model

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             clf__colsample_bytree=0.1, clf__max_depth=4, clf__n_estimators=25,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:squarederror', ...)

In [28]:
# predict the score of the trained model using the testing dataset
result = tuned_model.score(X_test, y_test)
print("R2 on test set : {}".format(result))

R2 on test set : 0.19377960084464463


In [29]:
# make predictions on the test data
y_predict = tuned_model.predict(X_test)
y_predict

array([ 8919.375 ,  8115.5186,  8115.5186, ...,  8115.5186, 43860.434 ,
        8115.5186], dtype=float32)

In [30]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from math import sqrt
k = X_test.shape[1]
n = len(X_test)
RMSE = float(format(np.sqrt(mean_squared_error(y_test, y_predict)),'.3f'))
MSE = mean_squared_error(y_test, y_predict)
MAE = mean_absolute_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)

print('RMSE =',RMSE, '\nMSE =',MSE, '\nMAE =',MAE, '\nR2 =', r2, '\nAdjusted R2 =', adj_r2) 

RMSE = 20396.621 
MSE = 416022140.0 
MAE = 12216.002 
R2 = 0.19377960084464463 
Adjusted R2 = 0.19272254389535626


In [31]:
# save tuned model locally
from joblib import dump, load
dump(tuned_model, '../model/tuned_xgb_model.joblib') 

['../model/tuned_xgb_model.joblib']

In [32]:
# load saved model and check functionality
tuned_model_loaded = load('../model/tuned_xgb_model.joblib')

In [33]:
tuned_model_loaded

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             clf__colsample_bytree=0.1, clf__max_depth=4, clf__n_estimators=25,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=10, n_jobs=0,
             num_parallel_tree=1, objective='reg:squarederror', ...)

In [34]:
# make predictions on the test data
y_predict = tuned_model_loaded.predict(X_test)
y_predict

array([ 8919.375 ,  8115.5186,  8115.5186, ...,  8115.5186, 43860.434 ,
        8115.5186], dtype=float32)

In [35]:
k = X_test.shape[1]
n = len(X_test)
RMSE = float(format(np.sqrt(mean_squared_error(y_test, y_predict)),'.3f'))
MSE = mean_squared_error(y_test, y_predict)
MAE = mean_absolute_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)

print('RMSE =',RMSE, '\nMSE =',MSE, '\nMAE =',MAE, '\nR2 =', r2, '\nAdjusted R2 =', adj_r2) 

RMSE = 20396.621 
MSE = 416022140.0 
MAE = 12216.002 
R2 = 0.19377960084464463 
Adjusted R2 = 0.19272254389535626
